//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Gym_HLV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaCTHD { get; set; }
        public int MaHD { get; set; }
        public Nullable<int> MaDKGT { get; set; }
        public Nullable<int> MaDKPT { get; set; }
        public Nullable<int> MaDKLop { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual DangKyPT DangKyPT { get; set; }
    }
}
