//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Gym_HLV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DangKyPT()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
            this.LichTapPT = new HashSet<LichTapPT>();
        }
    
        public int MaDKPT { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public int SoBuoi { get; set; }
        public decimal GiaMoiBuoi { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTapPT> LichTapPT { get; set; }
    }
}
