//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Gym_HLV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLop
    {
        public int MaLichLop { get; set; }
        public int MaLop { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime NgayHoc { get; set; }
        public System.TimeSpan GioBatDau { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
