//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Gym_HLV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.LichLop = new HashSet<LichLop>();
        }
    
        public int MaLop { get; set; }
        public string TenLop { get; set; }
        public int MaCM { get; set; }
        public decimal HocPhi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> SoBuoi { get; set; }
        public Nullable<int> SiSoToiDa { get; set; }
        public Nullable<int> SiSoHienTai { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual ChuyenMon ChuyenMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichLop> LichLop { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
